# Generated by Django 5.0.6 on 2024-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mission_assigned_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lion',
            name='quiz_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
