# Generated by Django 5.0.6 on 2024-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lion',
            name='mission_changes',
            field=models.IntegerField(default=0),
        ),
    ]
